import { ThemeProvider } from "@/app/context/ThemeContext.js"; // Import the ThemeProvider
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Navbar from "@/components/LandingPages/Navbar";
// import Footer from "@/components/LandingPages/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ACl Tear Detector",
  description: "App is generated by Next js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {/* Wrap with ThemeProvider */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
